# Generated by Django 5.2.12 on 2026-04-02 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=350, null=True)),
                ('short_intro', models.CharField(blank=True, max_length=250, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles/')),
                ('social_linkedin', models.CharField(blank=True, max_length=250, null=True)),
                ('social_github', models.CharField(blank=True, max_length=250, null=True)),
                ('social_insta', models.CharField(blank=True, max_length=250, null=True)),
                ('social_youtube', models.CharField(blank=True, max_length=250, null=True)),
                ('social_website', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
