# Generated by Django 5.2.12 on 2026-05-01 12:34

from django.db import migrations, models


def approve_existing_tags(apps, schema_editor):
    Tag = apps.get_model('projects', 'Tag')
    Tag.objects.update(is_approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(approve_existing_tags, migrations.RunPython.noop),
    ]
